### ISSUE TITLE
Wait for Service Hangs If service is already deleted or the service does not exist

### ISSUE THREAD

**Issue by dawu415** [patrickcrocker/cf-cli-resource#10]
The wait-for-service command hangs.

We can add a timeout, however, if it does timeout, the job fails.  It's probably better to add a check to make sure the service is actually there first.

**Comment by patrickcrocker** [comment]
What are the situations in which the `wait-for-service` command hangs?

**Comment by dawu415** [comment]
Hi Patrick,

1. We have a use case to delete a service, wait and then delete an Org.    However, if a service does not exist, the delete returns OK but nothing to delete and then wait-for-service will just sit there waiting for the service to be ready, when it does not exist. We need to wait because it takes about 1 minute for the service to de-provision.

2. Another scenario:  If we attempt to create a new service instance with 'wait for service' and the service instance already exists, create service will return OK service exists.   The "wait for service" will sit there just waiting for the pending to change to ok.

**Comment by patrickcrocker** [comment]
New in version 2.4.0:

`wait-for-service` command now exits with an error if the service does not exist.  This fixes the hang issue.  Please note that the `wait-for-service` command is specifically designed to "Wait for a service instance to **start**".  Instead, the `delete-service` command now supports the `wait_for_service` param specifically for deleting asynchronous services.  Not sure if we need a separate `wait-for-service-deletion` command yet, so please share your thoughts on that.

I also added test cases to test for creating service instances with the `wait-for-service` param for services instances that already exists.  Everything seems to pass, so let me know if you see something different!
