### ISSUE TITLE
cf_trace option question

### ISSUE THREAD

**Issue by marcus-sds** [patrickcrocker/cf-cli-resource#17]
Sorry for late resonse. I tested with your latest docker image.

When I use cf_trace option with "      command: create-service". there is an error.
just "push" worked as expected.
And error function seems "cf_wait_for_service_instance()"

=====error log
}
OK
[INFO] Waiting for service: xxx-rmq
parse error: Invalid numeric literal at line 2, column 8
parse error: Invalid numeric literal at line 2, column 8
parse error: Invalid numeric literal at line 2, column 8

**Comment by patrickcrocker** [comment]
v2.4.1 just released to fix this. Please read the release notes in the changelog!
