### ISSUE TITLE
create-user-provided-service failing when creating a service of the same name in different spaces within a single org

### ISSUE THREAD

**Issue by gm2552** [patrickcrocker/cf-cli-resource#20]
I have 2 spaces (staging and prod) within a single organization: 

My pipeline creates a user defined service in each of these spaces using the same service name in each space.  The service is created without issue in the first space, but fails when creating the service in the second space stating that a service with the same name already exists.  I have verified that the service does not exist in the second space, and the correct space name is being used when creating the service in the second space.  NOTE: it may not matter, but the services are created in 2 separated jobs within the pipeline.

**Staging Space**
_[INFO] Executing create-user-provided-service: luna
api endpoint:   https://api.sys.prod.us-west-2.cernercf.io
api version:    2.98.0
user:          <redacted>
org:            CernerDirect
space:          staging
Creating user provided service luna in org CernerDirect / space staging as cernerdirect-bot...
OK_

**Prod Space**
_[INFO] Executing create-user-provided-service: luna
api endpoint:   https://api.sys.prod.us-west-2.cernercf.io
api version:    2.98.0
user:           <redacted>
org:            CernerDirect
space:          prod
[INFO] Service luna already exists_

This can be easily reproduced by creating 2 spaces in an org and attempting to create a user defined service of the same name in the two different spaces.

**Comment by patrickcrocker** [comment]
Can you share a snippet of your pipeline.yml with the important bits?

**Comment by gm2552** [comment]
Let me know if you need more:
---------------------------------

resource_types:

- name: cf-cli-resource
  type: docker-image
  source:
    repository: pivotalpa/cf-cli-resource
    tag: latest

resources: 
.
.
.
# PCF resource for performing tasks in dev cloud foundry instance
- name: cf-cli-prod
  type: cf-cli-resource
  source: 
    api: ((cf-prod-api))
    username: ((cf-prod-username))
    password: ((cf-prod-password))
    skip_cert_check: true  
.
.
.
jobs:
                                         
- name: pave-staging-space
  build_logs_to_retain: 10
  plan:       
    - put: create-staging-services
      resource: cf-cli-prod
      params:
         commands:  
         - command: create-user-provided-service
           org: ((cf-org)) 
           space: ((cf-space-staging))    
           credentials: ((cf-staging-luna-config))
           service_instance: luna  
.
.
.
- name: pave-prod-space
  build_logs_to_retain: 10
  plan:       
    - put: create-staging-services
      resource: cf-cli-prod
      params:
         commands:   
         - command: create-user-provided-service
           org: ((cf-org)) 
           space: ((cf-space-prod))    
           credentials: ((cf-prod-luna-config))
           service_instance: luna

**Comment by patrickcrocker** [comment]
Got it.  I can reproduce this.  I should have a fix out in the next couple of days.

**Comment by patrickcrocker** [comment]
OK, I lied... this fix is simple and is being built in the CI pipeline now: 
https://wings.concourse.ci/teams/sme-pcf-concourse/pipelines/cf-cli-resource/jobs/build/builds/22

Once this passes the integration tests, I'll cut a release later today :-)

**Comment by gm2552** [comment]
Outstanding.  Thank you.

**Comment by patrickcrocker** [comment]
Fixed in v2.4.3/latest
