### ISSUE TITLE
Support for User Provided Services

### ISSUE THREAD

**Issue by shinmyung0** [patrickcrocker/cf-cli-resource#5]
I just gotta say, this is a great project.  This has been super helpful while playing around with concourse at my company. I was wondering though what you thought about providing support for the `cups` related command? We're currently using user-provided services to provide a uniform service binding interface to our apps while we figure out how to implement certain service brokers, it would great to be able to automate this part as well.

**Comment by patrickcrocker** [comment]
Implemented in v2.2.0/latest!  Please checkout the updated readme.

**Comment by shinmyung0** [comment]
Awesome thanks!
