### ISSUE TITLE
create-user-provided-service command is not idempotent

### ISSUE THREAD

**Issue by shinmyung0** [patrickcrocker/cf-cli-resource#6]
Because the create-user-provided service does not check if the `service_instance` is already in the space, it attempts to create another one which results in an error. I did manage to get around this by doing something like a `delete-service` inside of a `try` step, but it did catch me off guard since the other commands seem to be idempotent.

In the spirit of consistency maybe the same could be implemented here? I do see that a `cf_user_provided_service_exists` is already defined, so I think this could be done easily.

**Comment by patrickcrocker** [comment]
`create-user-provided-service` command no longer fails if there is an existing user provided service by the same name. NOTE: This is a departure from how the normal cf cups ... command works as it normally fails with an error:

  *Server error, status code: 400, error code: 60002, message: The service instance name is taken: my-cups-service*

See:
https://github.com/Pivotal-Field-Engineering/cf-cli-resource/releases/tag/v2.2.1

**Comment by SpencerKaiser** [comment]
@patrickcrocker I tried using both the original `cf cups` command and `cf create-user-provided-service` and both are failing with the error above. Am I doing something wrong?

``` shell
skaiser [~/...] > cf create-user-provided-service My-App-Name-Secrets -p '{"ADMINS":"${{ secrets.ADMINS }}","SLACK_SIGNING_SECRET":"${{ secrets.SLACK_SIGNING_SECRET }}", "SLACK_BOT_TOKEN": "${{ secrets.SLACK_BOT_TOKEN }}"}'
Creating user provided service My-App-Name-Secrets in org ***** / space ***** as *****@*****.com...
FAILED
Server error, status code: 400, error code: 60002, message: The service instance name is taken: My-App-Name-Secrets
skaiser [~/...] > cf -v
cf version 6.47.1+0921a21b7.2019-10-18
```

**Comment by patrickcrocker** [comment]
@SpencerKaiser `cf cups ...` will fail if the named service already exists.  If you need to update the existing service, you'll need to run `cf uups ...` (update-user-provided-service).

This is something that I take care of automatically in the `cf-cli-resource` ([see here](https://github.com/nulldriver/cf-cli-resource/blob/master/resource/lib/cf-functions.sh#L367)), but you'll need to handle on your own if running your own commands from the cli.

**Comment by SpencerKaiser** [comment]
Whoops, I misinterpreted the context of this issue. 

Thanks for the quick response; I'll have to do something similar on my end!

**Comment by holly-cummins** [comment]
From the linked issue, I think you've worked out that running `cf uups` in your GitHub action will work for you, is that right?
