### ISSUE TITLE
Delete Service and Unbind Service

### ISSUE THREAD

**Issue by dawu415** [patrickcrocker/cf-cli-resource#9]
Hi, 

We're trying to delete an Org, which requires a service to be deleted first. 
However, deleting a service needs to complete before an org can be deleted

Can there be a waitForDeleteServiceComplete in delete-service command?

Also, will there be an Unbind service?

**Comment by givett** [comment]
Hi,
I'm also hoping for an unbind-service command.
I create a service and bind it to an app.  But, I can't delete the service and the app without unbinding the service first.
Thanks!

**Comment by dawu415** [comment]
Yes, you can delete the app first and then delete the service.  The problem will be when you want to delete an Org/Space where a service lives in but cannot do that until service deletion completes. Some services may take about a min or more to complete de-provisioning.

**Comment by patrickcrocker** [comment]
Do you have an example of a service that takes a long time to delete?  I need to be able to reproduce this so I can write a test case around it.

**Comment by dawu415** [comment]
p-MySQL is the service that is being used.  It takes around 30sec+ to provision and deprovision.

**Comment by patrickcrocker** [comment]
Implemented in v2.4.0. Check the release notes!
